### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Jens-Wymeersch** [yeudas/PimaEspHome#1]
Dear @yeudas, I've been trying to get a connection to PIMA Alarm system without success. I see you did some work as well and were successful. Could you please help me understand what you have done and how I could do the same ?

**Comment by yeudas** [comment]
Hello @Jens-Wymeersch 
This project is really only started - and unfortunately I have no time to get back to it in the near future.
The status right now is that it is working in my house for several weeks - but it is crude and immature

The project suppose to run esp based board.
Do you know EspHome framework ?
EspHome can be integrate directly into HA - and from there create and upload firmware to esp boards.
the files I created are the files needed to make EspHome firmware that will communicate with PIMA
There is little remarks inside the files to what you need to change in order for it to adapt to your alarm

I suggest you look at the project I based my project on  -   https://github.com/deiger/Alarm
This project designed to run on RPI and with much better documentation

**Comment by Jens-Wymeersch** [comment]
Hi @yeudas thank you for your response. I am evaluating all my options at this moment. Could you please let me know which version of PIMA that you got it working ? I have HP896 and it might be too old. Thank you so much

**Comment by yeudas** [comment]
Hi @Jens-Wymeersch 
My PIMA system is also old - Hunter Pro 896 - seems like your HP896 - probably different naming according to country.
The other project is also meant for the same system but support better than mine.

I added two lines to what is needed to update in my code to adapt it to the specific implementation (technician code and sensors)

**Comment by Jens-Wymeersch** [comment]
@yeudas thank you. HP probably stands for Hunter Pro which basically means we have the same system. This means I need to be able to get this to work with your code. And we are most probably both living in Israel.

I’ve been in contact with Dror, trying to make the other projet work. As indicated I directly wired PIMA to the RPI but couldn’t get it to work.  

Possible reasons :
- I didn’t get his code to work properly
- the PIMA controller is still not set correctly to allow serial connection.
- Maybe I wired it wrongly 
- maybe you can’t coupling it directly to the RPI just doesn’t work. The serial indicates 12V whereas the RPI is at 5V. Would this make a difference ?

Now at least I know it’s not because of the version of the alarm system. 

Would it be possible to share your wiring of the system with me ? My e-mail is Jens.Wymeersch@gmail.com
